#!/usr/bin/env python3
"""Run dependency-free release checks for Artifact 3026."""

from __future__ import annotations

import importlib.util
import json
import re
import struct
import sys
import tempfile
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL_DIR = ROOT / ".agents" / "skills" / "artifact-3026"
SKILL_PATH = SKILL_DIR / "SKILL.md"
RENDERER_PATH = SKILL_DIR / "scripts" / "render_exhibit_card.py"
REPOSITORY = "https://github.com/xxwzkdwz/artifact-3026"
AI_BADGE_PATTERNS = (
    re.compile(r"\bAI[- ]?(?:ASSISTED|GENERATED)\b", re.IGNORECASE),
    re.compile(r"\b(?:CREATED|GENERATED) WITH AI\b", re.IGNORECASE),
    re.compile(r"\bGENERATED BY AI\b", re.IGNORECASE),
    re.compile(r"AI\s*辅助(?:生成|创作|虚构)?(?:内容)?", re.IGNORECASE),
    re.compile(r"AI\s*生成", re.IGNORECASE),
    re.compile(r"人工智能(?:生成|辅助)", re.IGNORECASE),
    re.compile(r"虚拟\s*生成", re.IGNORECASE),
)
VISIBLE_CARD_FIELDS = (
    "museum_name",
    "future_year",
    "artifact_name",
    "object_identity",
    "interpretation",
    "curator_note",
    "accession_no",
)


def fail(message: str) -> None:
    raise ValueError(message)


def contains_ai_badge(text: str) -> bool:
    return any(pattern.search(text) for pattern in AI_BADGE_PATTERNS)


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if not spec or not spec.loader:
        fail(f"cannot load {path.name}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def check_skill() -> None:
    text = SKILL_PATH.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        fail("SKILL.md is missing YAML frontmatter")
    frontmatter = text.split("---", 2)[1]
    required_patterns = {
        "name": r"^name:\s*artifact-3026\s*$",
        "description": r"^description:\s*\S.+$",
        "license": r"^license:\s*MIT\s*$",
        "author": r"^\s*author:\s*WANG ZHEN\s*$",
        "version": r'^\s*version:\s*"0\.2\.0"\s*$',
        "repository": rf"^\s*repository:\s*{re.escape(REPOSITORY)}\s*$",
    }
    missing = [label for label, pattern in required_patterns.items() if not re.search(pattern, frontmatter, re.MULTILINE)]
    if missing:
        fail("SKILL.md metadata mismatch: " + ", ".join(missing))
    if SKILL_DIR.name != "artifact-3026":
        fail("skill directory must match the frontmatter name")
    schema = (SKILL_DIR / "references" / "card-schema.md").read_text(encoding="utf-8")
    if "does not place AI-generation wording" not in schema:
        fail("card schema must prohibit AI-generation notices inside the card")
    if "Do not place AI-generation wording" not in text:
        fail("SKILL.md must prohibit AI-generation notices inside finished images")
    renderer_source = RENDERER_PATH.read_text(encoding="utf-8")
    if contains_ai_badge(renderer_source):
        fail("renderer source still contains an AI-generation badge")


def check_single_vendor_neutral_canonical_skill() -> None:
    skill_files = sorted(path for path in ROOT.rglob("SKILL.md") if ".git" not in path.parts)
    if skill_files != [SKILL_PATH]:
        found = ", ".join(str(path.relative_to(ROOT)) for path in skill_files)
        fail(f"expected one canonical SKILL.md, found: {found}")
    if (ROOT / ".codex-plugin").exists():
        fail(".codex-plugin must not be the primary delivery path")
    canonical_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in SKILL_DIR.rglob("*")
        if path.is_file() and path.suffix.lower() in {".md", ".py", ".json", ".yaml", ".yml"}
    )
    banned = ("Codex", "OpenAI", "Claude", "Cursor", "Copilot")
    present = [term for term in banned if term in canonical_text]
    if present:
        fail("canonical skill contains vendor-specific terms: " + ", ".join(present))
    required_neutral_terms = ("host agent", "available image-generation tool", "local execution environment")
    missing = [term for term in required_neutral_terms if term not in canonical_text]
    if missing:
        fail("canonical skill is missing neutral terminology: " + ", ".join(missing))


def check_license_readmes_and_compatibility() -> None:
    license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    if "MIT License" not in license_text or "Copyright (c) 2026 WANG ZHEN" not in license_text:
        fail("LICENSE does not match the declared MIT author metadata")
    chinese = (ROOT / "README.md").read_text(encoding="utf-8")
    english = (ROOT / "README.en.md").read_text(encoding="utf-8")
    if not re.search(r"[\u3400-\u9fff]", chinese) or "[English](README.en.md)" not in chinese:
        fail("root README must default to Chinese with a clear English entry")
    if "for AI assistants that support the open Agent Skills standard" not in english:
        fail("English README is missing the precise open-standard compatibility statement")
    for name, text in (("README.md", chinese), ("README.en.md", english)):
        if REPOSITORY not in text or "examples/meeting-room-paper-cup.svg" not in text:
            fail(f"{name} is missing the canonical URL or gallery evidence")
        if text.count('<img src="examples/cards/') != 7:
            fail(f"{name} must render one restrained hero and six visible gallery cards")
        if '<img src="examples/cards/meeting-room-paper-cup.png" width="400"' not in text:
            fail(f"{name} hero must be constrained to 400px")
        if text.count('width="180"') != 6:
            fail(f"{name} gallery must use six uniform 180px thumbnails")
    compatibility = (ROOT / "COMPATIBILITY.md").read_text(encoding="utf-8")
    for term in (
        "OpenAI / Codex",
        "Cursor",
        "GitHub Copilot",
        "Claude / Claude Code",
        "Qwen Code",
        "Kimi Code CLI",
        "火山引擎 AgentKit",
        "智谱 GLM",
        "agentskills.io/specification",
    ):
        if term not in compatibility:
            fail(f"compatibility matrix is missing {term}")
    naming = (ROOT / "docs" / "NAMING.md").read_text(encoding="utf-8")
    for term in ("Artifact 3026", "Future Relic", "skills.sh", "anthropics/skills", "github/awesome-copilot"):
        if term not in naming:
            fail(f"naming research is missing {term}")


def check_install_and_package_adapters() -> None:
    installer = load_module("install_skill", ROOT / "scripts" / "install_skill.py")
    packager = load_module("package_skill", ROOT / "scripts" / "package_skill.py")
    with tempfile.TemporaryDirectory() as temp_dir:
        temp = Path(temp_dir)
        agents_target = installer.target_path("agents", "project", temp)
        installer.install(SKILL_DIR, agents_target, "copy")
        if not (agents_target / "SKILL.md").is_file():
            fail("agents copy adapter did not install SKILL.md")
        claude_project = temp / "claude-project"
        claude_target = installer.target_path("claude", "project", claude_project)
        installer.install(SKILL_DIR, claude_target, "symlink")
        if not claude_target.is_symlink() or claude_target.resolve() != SKILL_DIR.resolve():
            fail("Claude symlink adapter does not point to the canonical skill")
        qwen_target = installer.target_path("qwen", "project", temp / "qwen-project")
        if qwen_target != ((temp / "qwen-project").resolve() / ".qwen" / "skills" / "artifact-3026"):
            fail("Qwen project adapter does not use .qwen/skills")
        kimi_target = installer.target_path("kimi", "project", temp / "kimi-project")
        if kimi_target != ((temp / "kimi-project").resolve() / ".agents" / "skills" / "artifact-3026"):
            fail("Kimi project adapter does not use .agents/skills")
        kimi_user_target = installer.target_path("kimi", "user", temp)
        if kimi_user_target != (Path.home() / ".config" / "agents" / "skills" / "artifact-3026"):
            fail("Kimi user adapter does not use the recommended user path")
        archive_path = packager.build(temp / "artifact-3026.zip")
        with zipfile.ZipFile(archive_path) as archive:
            names = set(archive.namelist())
        if "artifact-3026/SKILL.md" not in names:
            fail("portable ZIP is missing its root SKILL.md")
        if sum(name.endswith("SKILL.md") for name in names) != 1:
            fail("portable ZIP must contain one SKILL.md")
        if any(not name.startswith("artifact-3026/") for name in names):
            fail("portable ZIP must keep every file under one AgentKit-compatible root directory")


def check_examples() -> None:
    renderer = load_module("artifact_3026_renderer", RENDERER_PATH)
    inputs = sorted((ROOT / "examples").glob("*.json"))
    if len(inputs) != 6:
        fail(f"expected 6 public examples, found {len(inputs)}")
    tones: set[str] = set()
    chinese_examples = 0
    for input_path in inputs:
        data = json.loads(input_path.read_text(encoding="utf-8"))
        tones.add(str(data.get("tone", "")))
        chinese_examples += bool(re.search(r"[\u3400-\u9fff]", str(data.get("artifact_name", ""))))
        image_path = Path(str(data.get("image_path", "")))
        if image_path.is_absolute() or image_path.parts[:1] != ("scenes",):
            fail(f"example image_path must be a portable scenes/ path: {input_path.name}")
        scene_path = input_path.parent / image_path
        if not scene_path.is_file():
            fail(f"missing generated scene: {scene_path.relative_to(ROOT)}")
        scene_payload = scene_path.read_bytes()
        if not scene_payload.startswith(b"\xff\xd8\xff"):
            fail(f"invalid JPEG scene: {scene_path.relative_to(ROOT)}")
        if contains_ai_badge(scene_payload.decode("latin-1")):
            fail(f"JPEG metadata contains an AI-generation notice: {scene_path.relative_to(ROOT)}")
        if data.get("scene_source") != "AI-generated from text for this repository; see examples/SOURCES.md":
            fail(f"missing scene provenance: {input_path.name}")
        visible_copy = "\n".join(str(data.get(field, "")) for field in VISIBLE_CARD_FIELDS)
        if contains_ai_badge(visible_copy):
            fail(f"visible card copy contains an AI-generation notice: {input_path.name}")
        rendered = renderer.render(data, base_dir=input_path.parent)
        output_path = input_path.with_suffix(".svg")
        if not output_path.is_file() or output_path.read_text(encoding="utf-8") != rendered:
            fail(f"missing or stale generated example: {output_path.relative_to(ROOT)}")
        if contains_ai_badge(rendered):
            fail(f"generated SVG contains an AI-generation notice: {output_path.relative_to(ROOT)}")
        card_path = ROOT / "examples" / "cards" / f"{input_path.stem}.png"
        payload = card_path.read_bytes()
        if payload[:8] != b"\x89PNG\r\n\x1a\n" or len(payload) < 24:
            fail(f"invalid PNG card: {card_path.relative_to(ROOT)}")
        if struct.unpack(">II", payload[16:24]) != (1080, 1440):
            fail(f"wrong PNG card dimensions: {card_path.relative_to(ROOT)}")
        if contains_ai_badge(payload.decode("latin-1")):
            fail(f"PNG metadata contains an AI-generation notice: {card_path.relative_to(ROOT)}")
    if tones != {"deadpan", "tender", "absurd"} or chinese_examples != 3:
        fail("gallery must cover three tones and contain three Chinese examples")
    if not (ROOT / "examples" / "SOURCES.md").is_file():
        fail("example image provenance record is missing")


def check_repository_hygiene() -> None:
    required = [
        ROOT / "LICENSE",
        ROOT / "README.md",
        ROOT / "README.en.md",
        ROOT / "COMPATIBILITY.md",
        ROOT / "docs" / "NAMING.md",
        SKILL_PATH,
        RENDERER_PATH,
        ROOT / "scripts" / "install_skill.py",
        ROOT / "scripts" / "package_skill.py",
    ]
    missing = [str(path.relative_to(ROOT)) for path in required if not path.is_file()]
    if missing:
        fail("missing required files: " + ", ".join(missing))
    if "output/" not in (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines():
        fail("local trial output must remain excluded from the public repository")
    placeholder_marker = "[TO" + "DO:"
    for path in ROOT.rglob("*"):
        if path.is_file() and ".git" not in path.parts and path.suffix.lower() in {".md", ".json", ".py", ".yaml", ".yml"}:
            if placeholder_marker in path.read_text(encoding="utf-8"):
                fail(f"unfinished placeholder in {path.relative_to(ROOT)}")


def main() -> int:
    checks = [
        ("open skill metadata", check_skill),
        ("single vendor-neutral canonical skill", check_single_vendor_neutral_canonical_skill),
        ("license, readmes, compatibility, and naming", check_license_readmes_and_compatibility),
        ("copy, symlink, and ZIP adapters", check_install_and_package_adapters),
        ("generated examples", check_examples),
        ("repository hygiene", check_repository_hygiene),
    ]
    for label, check in checks:
        check()
        print(f"ok: {label}")
    print("release validation passed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError, zipfile.BadZipFile) as error:
        print(f"release validation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
